<div class="row">
    <div class="col-md-12">
        <div class="form-group">
            <label for="comment">About</label>
        </div>
        <div>
            <p>
                This website was written using Phalcon framework. Provide next functions:
            </p>
            <ul>
                <li><a href="/"><strong>Hash.</strong></a> Generate hash from string</li>
                <li><a href="/password"><strong>Password.</strong></a> Generate password using custom parameters</li>
                <li><a href="/random"><strong>Random.</strong></a> Generate string with random symbols</li>
                <li><a href="/uuid"><strong>Uuid.</strong></a> Generate uuids with different types</li>
                <li><a href="/json"><strong>Json.</strong></a> Validate json string</li>
                <li><a href="/base64"><strong>Base64.</strong></a> Convert from-to Base64 algorithm</li>
            </ul>
        </div>
    </div>
</div>